### ISSUE TITLE
Support for specifying texture to use for snowy terrain

### ISSUE THREAD

**Issue by mr-bo-jangles** [jetelain/ArmaRealMap#139]
Currently there are some issues generating terrain which contains mountain or snow covered peaks. It appears to be related to the inability for us to specify a snow based texture for regions which would be snow, so it falls back to default ground maybe?

Distant view
![image](https://github.com/jetelain/ArmaRealMap/assets/291570/739c50fc-3d57-4bf9-8c99-7d74e4f6d16b)

Up Close
![image](https://github.com/jetelain/ArmaRealMap/assets/291570/070b0ca3-98f0-4954-aa13-55e6aead481e)

**Comment by mr-bo-jangles** [comment]
Oh, I can add my own surface textures in the studio based on these tags? I must have missed how to do this in the documentation

**Comment by jetelain** [comment]
It's not yet possible, it's an evolution I have to do
