### ISSUE TITLE
Tagging fence and wall variations

### ISSUE THREAD

**Issue by Autoclock** [jetelain/ArmaRealMap#141]
Allow us to tag fence and wall variations so we can tell GRM to generate specific types of fences in certain areas.
I don't think it's totally compatible with the current implementation with probabilities but it would be nice to guarantee them in certain areas.

So something like this might work with tags for example:
![image](https://github.com/jetelain/ArmaRealMap/assets/56294342/b26d55be-6ce2-4b21-b2dd-bd1882aca384)

**Comment by jetelain** [comment]
Hi,
It's a planned feature. Current implementations is based on points, here it should be based on path. But there is some edges cases hard to process like if a wall is between a military and residential area, should it be "IsMilitary", "IsResidential" or both ? For the specific case I would answer "IsMilitary", but there is a lot of edge cases to consider, it will take more time to find out the correct approach.

**Comment by mr-bo-jangles** [comment]
You could likely get most of the way there with a priority system. 

The highest priority matching result in the list is preferred.

Equal priority items fall back to current logic

**Comment by Autoclock** [comment]
I agree with the priority list idea, something like: Military > Residential > Farmland/Farmyard
