### ISSUE TITLE
GRM does not generate driveways

### ISSUE THREAD

**Issue by Autoclock** [jetelain/ArmaRealMap#147]
driveways are not being generated as roads by GRM
the tags are as follows:
highway=service
service=driveway

**Comment by jetelain** [comment]
Hi,
It is an intentional limitation to avoid having too much roads. 
I will add a configuration to bypass this limitation.

**Comment by Autoclock** [comment]
Ah I see, in the area I am working in rural areas where marked driveways are often long

**Comment by jetelain** [comment]
Hi, I opted for a threshold. Private service roads below this threshold will be ignored. The threshold can be configured per-map, default value is 25m. To keep everything, value can be set to 0.
