### ISSUE TITLE
Underwater roads should probably not have streetlights?

### ISSUE THREAD

**Issue by mr-bo-jangles** [jetelain/ArmaRealMap#148]
We should probably work out how to tell if the road is going underwater and if so avoid putting streetlights on the road
![image](https://github.com/jetelain/ArmaRealMap/assets/291570/b01b9a74-41ae-408e-a8ed-19477655a706)

**Comment by jetelain** [comment]
Hi,
Yes it should be avoided. Meanwhile you can add a condition in the asset configuration.

![image](https://github.com/jetelain/ArmaRealMap/assets/33651126/f654a10a-14a5-4ddf-b876-311b0247012b)
