### ISSUE TITLE
Density variation within large areas of 1 land type

### ISSUE THREAD

**Issue by mr-bo-jangles** [jetelain/ArmaRealMap#160]
I've generated a few maps at this point and I'm noticing a recurring theme of large areas of forest or grassland being very uniform in distribution. 

Obviously the tree placement is random, however it doesn't change in density for kilometers at a time and it's fairly noticeable.

Is there any way I can tell the tool to vary density if the region is getting too big?

**Comment by jetelain** [comment]
Hi,
Density is chosen randomly for the full area. Current version is not able to have a non-uniform density for a given area.
Density variation seems difficult to implement within a single area. I think the best would to split large areas in smaller ones and then fill those smaller areas with a random density. With this approach, the question would be to found an efficient way to split large areas with random shapes.

**Comment by mr-bo-jangles** [comment]
https://www.chiark.greenend.org.uk/~sgtatham/quasiblog/aperiodic-spectre/

**Comment by jetelain** [comment]
Hi,
Splitting shapes is still an option, but I'm also exploring "non uniform random position generator" to create density variations based on a noise generator (testing Perlin noise)

Example on a 1000x1000m square with 10k positions
![image](https://github.com/jetelain/ArmaRealMap/assets/33651126/096612b5-35c7-4bbd-9dd7-e491f1399993)

**Comment by mr-bo-jangles** [comment]
Awesome, thanks for the update!
