### ISSUE TITLE
Need more informative error messages

### ISSUE THREAD

**Issue by Ajdj100** [jetelain/ArmaRealMap#169]
While building an asset configuration I accidentally left an empty seed of Scrubs, which caused my build to fail. The only error message I got was:

> Exception: System.AggregateException: One or more errors occurred. (Sum of probability must be 1, but is 0) (Sum of probability must be 1, but is 0) (Sum of probability must be 1, but is 0) (Sum of probability must be 1, but is 0) (Sum of probability must be 1, but is 0) (Sum of probability must be 1, but is 0) (Sum of probability must be 1, but is 0)

I happened to have changed some probability values in the Scrubs options so I happened to go back and check it and found the empty seed, but it would be nice to have some error reporting or warnings to tell you where the issue is on the user facing side.

**Comment by jetelain** [comment]
Hi,
The best would to have no error at all, the editor should not allow you to save a file with an error and should incidates where the error is.
For this specific error case, I've made a change in #159 to avoid the error by ignoring the empty variations. I think I should something similar with seeds.
