### ISSUE TITLE
Question about landgrid

### ISSUE THREAD

**Issue by wwwronin** [jetelain/ArmaRealMap#20]
Hi,
I want to know how to compute the materials index when writing wrp file. I see in the code ,but do not understand. And the landrange why be 1024 when terrain size is larger than 30km.And what is the relationship of sat image tile(eg size is 1024 or 2048etc.) and land grid.

**Comment by jetelain** [comment]
Hi,

Terrain is build with three grids:
- elevation grid
- land grid
- sat image / id image grid

Land grid will have a direct effect on game performance (I think game engine does a draw call per cell). Land grid have also an effect how clutter is generated.
Land grid is a power of two and exactly match terrain size. Each part have an arbitrary size.

Sat image / id image grid is built to have each tile a valid image size (power of two), and a small overlap to reduce the number of tiles to be loaded at the same time. This grid does not match terrain, it always overflow.

The indexes are here to give the relation between the two grids, the algorithm find which sat image tile has to be used for each cell of land grid. For each cell of landgrid, it computes which sat map tile has to be used.

As the real algorithm is not documented, it have been a lot of trial and error to get the current algorithm.

The choice of land grid is arbitrary. In the first generator, I had pick 512 as "one size fits all", but it lead to issues on clutter generation in game for small maps. I've made some testings and choosed the current values. The generator have been tested on up to 80 Km, larger landgrid might be possible. Terrain builder seems to accept generating up to 8192x8192, but it needs testing to be sure about that.

On some recent tests, the tile size should not be the default value (1024) for small maps, as grid can't match (it creates artefacts). I will change that in an upcoming pull request.

The code is licensed under MIT, you can freely reuse it.

**Comment by jetelain** [comment]
I've found out my implementation has issues, the real algorithm have been found out by pennyworth12345, see https://github.com/pennyworth12345/A3_MMSI/wiki/Mapframe-Information
