### ISSUE TITLE
Forest inner ways: road/path or cutline

### ISSUE THREAD

**Issue by Slord6** [jetelain/ArmaRealMap#230]
Hi!

A couple of (I think) related issues with forests/woodland.

Ways through forests generated with this tool often have trees encroaching on the path/road which is usually inaccurate. This can make driving on the roads in Arma difficult.

Similarly there is a tag for [cutlines](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dcutline) ([for example](https://www.openstreetmap.org/way/446365955#map=14/45.9011/-74.4610)), which I came across recently and I suspect support for those would be a similar issue?

**Comment by jetelain** [comment]
Hi,
Roads are already excluded from forest. But "service" / "private" roads are ignored in current implementation, to avoid having too much roads (#147). I'm planning to add some configuration for that, or have a threshold.
Adding cutline should be difficult, it could reuse some parts of the road processing.

**Comment by jetelain** [comment]
Adding support for cutlines :  #240

**Comment by jetelain** [comment]
I've added a threshold for private service road #241. On provided example (Lac des Seize), it allows to take into account all paths.

**Comment by Slord6** [comment]
That's great, thanks Julien

**Comment by jetelain** [comment]
Hi, it's available in pre-release : https://github.com/jetelain/ArmaRealMap/releases/tag/v0.10.3
