### ISSUE TITLE
Unable to read beyond the end of the stream

### ISSUE THREAD

**Issue by nordbearbotdev** [jetelain/ArmaRealMap#246]
during the rebuild of the world, a malfunction occurred, as a result of which my world.wrp gives the error "Unable to read beyond the end of the stream", what should I do?

**Comment by jetelain** [comment]
Hi, can you generate an error with the Help menu ? it will gives more details on what went wrong

**Comment by jetelain** [comment]
Hi, I was not able to reproduce. Feel free to re-open if you still have the problem, or to contact me on Discord (see https://github.com/jetelain/ArmaRealMap/wiki/Support)
