### ISSUE TITLE
Can't generate the map, i get this error message

### ISSUE THREAD

**Issue by SgtSirboni** [jetelain/ArmaRealMap#56]
'Download from OSM' done in 00:03:15.0239434
Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 195 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: I/O operation terminated due to thread exit or application request.
 ---> System.Net.Sockets.SocketException (995): I/O operation terminated due to thread exit or application request.

**Comment by jetelain** [comment]
Hi, 
It's an issue related to OpenStreetMap, it does not respond in the timeout I have set (195 seconds). 
Maybe the region is too large, or you may have used all your processing quota (based on IP address I guess).
I can change the timeout for a larger value, It may works.

**Comment by SgtSirboni** [comment]
Thanks, that might help. Anyways I have tried a few more times and eventually it worked.
