### ISSUE TITLE
System.ComponentModel.Composition.CompositionException

### ISSUE THREAD

**Issue by Red1042** [jetelain/ArmaRealMap#75]
An exception occurred while trying to create an instance of type 'GameRealisticMap.Studio.Modules.Reporting.ViewModels.ProgressToolViewModel'.

Happens every time I try to use the "Generate Mod" button, no matter what is selected for PBO generation or where the selection box is on the map.

[studio_2023-08-07.txt](https://github.com/jetelain/ArmaRealMap/files/12286802/studio_2023-08-07.txt)

**Comment by jetelain** [comment]
Similar to issue #49. Likely the CPU counter is not able to initialize. Will make it optional.

**Comment by jonvelz** [comment]
> An exception occurred while trying to create an instance of type 'GameRealisticMap.Studio.Modules.Reporting.ViewModels.ProgressToolViewModel'.
> 
> Happens every time I try to use the "Generate Mod" button, no matter what is selected for PBO generation or where the selection box is on the map.
> 
> [studio_2023-08-07.txt](https://github.com/jetelain/ArmaRealMap/files/12286802/studio_2023-08-07.txt)

Do you have some sort of hardware monitor program?

**Comment by Red1042** [comment]
I have a couple of hardware monitoring programs like GPU-Z, CPU-Z, and AMD Software (built in to the graphics card).

**Comment by jetelain** [comment]
Version with the fix have been released, If you have still an issue you can reopen this issue.
