### ISSUE TITLE
Releasing .exe files alongside github releases

### ISSUE THREAD

**Issue by Hubix9** [jetelain/ArmaRealMap#81]
Hello, I have a question. Could you please release an .exe build of this tool with each github release? It would be of great help to people who don't use microsoft store, but also for those that would like to use a specific version of the app without recompiling the project themselves, since MS store doesn't allow for installing a specific app version.

By the way your tool is amazing, thank you very much for sharing it 😊

**Comment by jetelain** [comment]
Hello, I've attached binaries for Beta 4 (appxbundle / exe and dependencies zipped).

**Comment by jetelain** [comment]
I will do the same for next updates
